### ISSUE TITLE
Removing unecessary spacing

### ISSUE THREAD

**Issue by shreyneil** [shreyneil/Airline_Delay_Predictor#3]

**Comment by manasivaraiya** [comment]
can i contribute??

**Comment by shreyneil** [comment]
sure, Please, i''ll keep my PR at hold .

**Comment by manasivaraiya** [comment]
what exactly has to be done??
can you provide a description??

**Comment by shreyneil** [comment]
Removing the extra spacing, see if there is no identation problem and create a PR.

**Comment by manasivaraiya** [comment]
Remove extra spacing from what?? Which document??

**Comment by shreyneil** [comment]
Thanks @manasivaraiya 😄
